// Generated by CoffeeScript 1.8.0
(function() {
  var body, doTest, testCSS, wcStyle;

  doTest = function(message, fn) {
    console.log(message);
    return fn(function(err, resp) {
      if (err) {
        return console.log("" + err);
      }
      return console.log("" + resp);
    });
  };

  if (wcStyle = window.WC.style) {
    console.log('window.WC.style ok');
  }

  wcStyle.init();

  if (document.getElementById('wcStyle')) {
    console.log('wcStyle.init ok');
  }

  testCSS = '.test{}';

  wcStyle.addCss(testCSS);

  if (document.getElementById('wcStyle').innerText.search(testCSS) !== -1) {
    console.log('wcStyle.add ok');
  }

  wcStyle.render();

  if (document.getElementById('wcStyle').innerText.search('//version:0.0.1;') !== -1) {
    console.log('wcStyle.render ok');
  }

  body = {
    margin: 0,
    padding: 0
  };

  doTest('Test wcStyle.val', function(fn) {
    wcStyle.val('body', body);
    testCSS = 'body{margin:0;padding:0;}';
    if (document.getElementById('wcStyle').innerText.search(testCSS) !== -1) {
      return fn(null, 'ok');
    } else {
      return fn('error');
    }
  });

  doTest('Test wcStyle.val [object]', function(fn) {
    testCSS = '.body{margin:0;padding:0;}';
    wcStyle.val({
      '.body': body
    });
    if (document.getElementById('wcStyle').innerText.search(testCSS) !== -1) {
      return fn(null, 'ok');
    } else {
      return fn('error');
    }
  });

}).call(this);

//# sourceMappingURL=test.js.map
